manifest:
  remotes:
    - name: lunigorn
      url-base: https://github.com/Lunigorn
  projects:
    - name: zmk
      remote: lunigorn
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: lunigorn
      revision: main
  self:
    path: config
